---
- name: Update OS
  ansible.builtin.apt:
    update_cache: yes

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - python3-pip # for get_url download public key
      - python3-venv # rof test
    state: present

- name: Vars for inventory
  include_vars: vars/inventory.yml

- include_tasks: groups.yml
- include_tasks: users-create.yml
- include_tasks: users-disable.yml
- include_tasks: disable-work.yml
